### ISSUE TITLE
GuestAdditions take a REALLY long time to install.

### ISSUE THREAD

**Issue by duro** [ailispaw/rancheros-lite#3]
For some reason on this box, my guest-additions plugin takes a REALLY long time to install the GuestAdditions that match my VirtualBox. I have used other docker base boxes in the past and they never take this long to install. Any idea why?

**Comment by ailispaw** [comment]
It has GuestAdditions partially to use the syncd folder.
You don't need to install GuestAdditions additionally.

I wonder if that installation is completed after such a long time.

**Comment by ailispaw** [comment]
Is your guest-additions plugin `vagrant-vbguest`?
If so, please add the following into your Vagrantfile for rancheros-lite.

```
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
```

Although GuestAdditions v4.3.30 in rancheros-lite currently works fine with VirtualBox v5.0.0,
I have a plan to upgrade GuestAdditions to v5.0.0.

Thanks.

**Comment by ailispaw** [comment]
@duro How about this?

**Comment by duro** [comment]
It was indeed that plugin. Disabling it fixed the issue.

AD
