### ISSUE TITLE
Persisting data between vagrant reloads

### ISSUE THREAD

**Issue by duro** [ailispaw/rancheros-lite#4]
I have set up a host volume mount to a postgres container that mounts to /volumes/project/postgres on the host. However when I run a vagrant reload on the VM that rancheros-lite is spun up on, the /volumes folder is gone. Is there somewhere specific in the box that I should mount volumes that I want to persist?

**Comment by ailispaw** [comment]
You can use any folder under `/mnt/sda1`, because it mounts the persistent disk on `/mnt/sda1`.

If you use Vagrant NFS syncd folder as follows, you can use any folder under `/vagrant/` as well.

```
config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ["nolock", "vers=3", "udp"]
```

**Comment by duro** [comment]
Yep, just figured this one out. Seems I can use /opt as well.

**Comment by ailispaw** [comment]
Yes, it is linked to `/mnt/sda1/opt/`.

**Comment by ailispaw** [comment]
`/home` as well.
