### ISSUE TITLE
Up Docker version

### ISSUE THREAD

**Issue by cedvan** [ailispaw/rancheros-lite#8]
Hi,

It's a great vagrant box !
Upgrade docker version is possible please ?

Thank you

**Comment by ailispaw** [comment]
Hi @cedvan ,

This project has been depreciated and succeeded by DockerRoot.
https://atlas.hashicorp.com/ailispaw/boxes/docker-root

Please consider using DockerRoot instead.
It still has Docker v1.9.1, but the latest Docker will be in the next release.

**Comment by cedvan** [comment]
Oo, sorry.

I'll try `docker-root` !

Thank you
